name: Qa
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  code-styles:
    name: code-styles
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga
  composer-validate:
    name: composer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: composer-normalize-action
        uses: docker://localheinz/composer-normalize-action:0.4.2