name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  php-7-1:
    name: php 7.1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        uses: docker://php:7.1-cli
      - name: phpunit
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar install
          vendor/bin/phpunit
  php-7-2:
    name: php 7.2
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        uses: docker://php:7.2-cli
      - name: phpunit
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar install
          vendor/bin/phpunit
  php-7-3:
    name: php 7.3
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - uses: docker://php:7.3-cli
      - name: phpunit
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar install
          vendor/bin/phpunit